services:
  MicroRegBaseline:
    build:
      context: ../
      dockerfile: docker_src/Dockerfile
    image: micro-reg-baseline
    container_name: MicroRegBaseline
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      - HOST_HOME=${HOST_HOME}
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ../:/root/Software/microReg-Baseline
      - ${HOST_HOME}:/root/YourLocalHome